[build]
builder = "dockerfile"

[deploy]
startCommand = "./main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
# Ensure Go version if using nixpacks fallback
GO_VERSION = "1.23.5"
